package it.unipi.lsmd.gastronomate.dao.exceptions.enums;

public enum ErrorTypeEnum {
    DATABASE_ERROR,
    DUPLICATED_ERROR,
    NOT_FOUND_ERROR,
    CONNECTION_ERROR, INVALID_DATA, DUPLICATED_ELEMENT, TRANSIENT_ERROR, CLIENT_ERROR, SESSION_ERROR, AUTHENTICATION_ERROR, ACCOUNT_STATUS_ERROR, GENERIC_ERROR
}
